// Docs: https://www.instantdb.com/docs/permissions

import type { InstantRules } from '@instantdb/react'

const rules = {
  maps: {
    bind: [
      'isOwner',
      'auth.id != null && auth.id in data.ref("creator.id")',
      'hasReadPermission',
      'auth.id != null && auth.id in data.ref("readPermissions.id")',
      'hasWritePermission',
      'auth.id != null && auth.id in data.ref("writePermissions.id")',
      'hasManagePermission',
      'auth.id != null && auth.id in data.ref("managePermissions.id")',
      'hasPendingInvitation',
      'auth.id != null && ((auth.id in data.ref("shareInvitations.invitedUserId") || (auth.email != null && auth.email in data.ref("shareInvitations.invitedEmail"))) && "pending" in data.ref("shareInvitations.status")) || (auth.email != null && auth.email in data.ref("shareInvitations.invitedEmail") && "pending" in data.ref("shareInvitations.status"))',
      'isOwnerOrReader',
      'isOwner || hasReadPermission || hasWritePermission || hasManagePermission || hasPendingInvitation',
      'isOwnerOrEditor',
      'isOwner || hasWritePermission || hasManagePermission || hasPendingInvitation',
      'isOwnerOrManager',
      'isOwner || hasManagePermission',
    ],
    allow: {
      view: 'isOwnerOrReader',
      create: 'auth.id != null',
      delete: 'isOwner',
      update: 'isOwnerOrEditor',
    },
  },
  $users: {
    allow: {
      view: 'auth.id != null',
    },
  },
  shares: {
    bind: [
      'mapOwnerOnly',
      'auth.id != null && auth.id in data.ref("creator.id")',
      'hasManagePermission',
      'auth.id != null && auth.id in data.ref("map.managePermissions.id")',
      'isOwnerOrManager',
      'mapOwnerOnly || hasManagePermission',
      'shareRecipient',
      'auth.id != null && auth.id in data.ref("user.id")',
      'isActiveShare',
      'data.status == "active"',
      'isEditShare',
      'data.permission == "edit"',
      'canViewShares',
      'isOwnerOrManager || (shareRecipient && isActiveShare)',
      'shareRecipientWithEdit',
      'shareRecipient && isActiveShare && isEditShare',
      'mapOwnerOrEditShareRecipient',
      'isOwnerOrManager || shareRecipientWithEdit',
      'hasInvitationForMap',
      '(auth.id != null && auth.id in data.ref("map.shareInvitations.invitedUserId")) || (auth.email != null && auth.email in data.ref("map.shareInvitations.invitedEmail"))',
      'hasPendingInvitationForMap',
      'hasInvitationForMap && "pending" in data.ref("map.shareInvitations.status")',
      'canUpdateLinkedInvitation',
      'data.invitation != null && ((auth.id != null && auth.id in data.ref("invitation.invitedUserId")) || (auth.email != null && auth.email in data.ref("invitation.invitedEmail")))',
      'ownerOrInvitee',
      'isOwnerOrManager || hasInvitationForMap || canUpdateLinkedInvitation',
    ],
    allow: {
      view: 'canViewShares',
      create: 'ownerOrInvitee',
      delete: 'isOwnerOrManager',
      update: 'isOwnerOrManager',
    },
  },
  folders: {
    bind: ['isOwner', 'auth.id != null && auth.id in data.ref("creator.id")'],
    allow: {
      view: 'auth.id != null',
      create: 'auth.id != null',
      delete: 'isOwner',
      update: 'isOwner',
    },
  },
  concepts: {
    bind: [
      'mapIsOwned',
      'auth.id != null && auth.id in data.ref("map.creator.id")',
      'mapHasReadPermission',
      'auth.id != null && auth.id in data.ref("map.readPermissions.id")',
      'mapHasWritePermission',
      'auth.id != null && auth.id in data.ref("map.writePermissions.id")',
      'mapHasManagePermission',
      'auth.id != null && auth.id in data.ref("map.managePermissions.id")',
      'canReadParentMap',
      'mapIsOwned || mapHasReadPermission || mapHasWritePermission || mapHasManagePermission',
      'canEditParentMap',
      'mapIsOwned || mapHasWritePermission || mapHasManagePermission',
    ],
    allow: {
      view: 'canReadParentMap',
      create: 'canEditParentMap',
      delete: 'canEditParentMap',
      update: 'canEditParentMap',
    },
  },
  perspectives: {
    bind: [
      'mapIsOwned',
      'auth.id != null && auth.id in data.ref("map.creator.id")',
      'mapHasReadPermission',
      'auth.id != null && auth.id in data.ref("map.readPermissions.id")',
      'mapHasWritePermission',
      'auth.id != null && auth.id in data.ref("map.writePermissions.id")',
      'mapHasManagePermission',
      'auth.id != null && auth.id in data.ref("map.managePermissions.id")',
      'canReadParentMap',
      'mapIsOwned || mapHasReadPermission || mapHasWritePermission || mapHasManagePermission',
      'canEditParentMap',
      'mapIsOwned || mapHasWritePermission || mapHasManagePermission',
    ],
    allow: {
      view: 'canReadParentMap',
      create: 'canEditParentMap',
      delete: 'canEditParentMap',
      update: 'canEditParentMap',
    },
  },
  relationships: {
    bind: [
      'mapIsOwned',
      'auth.id != null && auth.id in data.ref("map.creator.id")',
      'mapHasReadPermission',
      'auth.id != null && auth.id in data.ref("map.readPermissions.id")',
      'mapHasWritePermission',
      'auth.id != null && auth.id in data.ref("map.writePermissions.id")',
      'mapHasManagePermission',
      'auth.id != null && auth.id in data.ref("map.managePermissions.id")',
      'canReadParentMap',
      'mapIsOwned || mapHasReadPermission || mapHasWritePermission || mapHasManagePermission',
      'canEditParentMap',
      'mapIsOwned || mapHasWritePermission || mapHasManagePermission',
    ],
    allow: {
      view: 'canReadParentMap',
      create: 'canEditParentMap',
      delete: 'canEditParentMap',
      update: 'canEditParentMap',
    },
  },
  shareInvitations: {
    bind: [
      'mapOwnerCreator',
      'auth.id != null && auth.id in data.ref("creator.id")',
      'hasManagePermission',
      'auth.id != null && auth.id in data.ref("map.managePermissions.id")',
      'isOwnerOrManager',
      'mapOwnerCreator || hasManagePermission',
      'authMatchesInvitee',
      '(auth.id != null && (auth.id == data.invitedEmail || auth.id == data.invitedUserId)) || (auth.email != null && (auth.email == data.invitedEmail || auth.email == data.invitedUserId))',
      'mapOwnerOrInvitee',
      'mapOwnerCreator || authMatchesInvitee',
      'canViewInvitations',
      'isOwnerOrManager || authMatchesInvitee',
    ],
    allow: {
      view: 'canViewInvitations',
      create: 'isOwnerOrManager',
      delete: 'isOwnerOrManager',
      update: 'isOwnerOrManager || authMatchesInvitee',
    },
  },
} satisfies InstantRules

export default rules
